[package]
name    = "mensa_bot"
version = "0.1.0"

[dependencies]
env_logger   = "0.4"
log          = "0.3"
regex        = "0.2"
reqwest      = "0.8"
select       = "0.4"
serde        = "1.0"
serde_derive = "1.0"
serde_json   = "1.0"
time         = "0.1"
toml         = "0.4"
